### ISSUE TITLE
Shared Data Stewardship

### ISSUE THREAD

**Issue by ekrimmel** [paleo-data/happy-hours#7]
## What is your idea for a happy hour topic?
This topic is about how museums are managing data for shared collections. At the specimen level, this could include a fossil with part and counterpart stored/cataloged at different institutions. On the larger scale, multiple institutions could have hundreds or thousands of specimens collected from the same locality (or by the same person). A similar situation may occur when multiple institutions have casts of an in situ fossil located elsewhere. This happy hour will be an introduction to the types of shared collections described above in order to facilitate discussion on how we manage shared data.

Relates to Little et al. talk at BioDigiCon 2022: [What does digitizing fossils in situ mean for museum collections and our data ecosystem?](https://drive.google.com/file/d/18euYMDtafOkzmOIPu2T6l53KKb0LsJpN/view?usp=sharing). Also to work happening in the TDWG materialSample group.

## Who could be involved in leading this happy hour?
Amanda Millhouse, Christina Byrd?, Nicole Volden?

## Are there any timing considerations?
Tentatively scheduled for 2024-03-21, but could also go earlier in the year

## Next steps
This issue captures a happy hour topic idea. Once you are ready to finalize an idea and put it on the PDWG happy hour schedule, please create a new issue using the [Plan a happy hour](https://github.com/paleo-data/happy-hours/issues/new?assignees=&labels=PDWG&projects=&template=plan-happy-hour.md&title=%5Breplace+this+text+with+the+happy+hour+topic%5D) template. **Then, close this issue.**

**Comment by RogerBurkhalter** [comment]
@ekrimmel, as this issue is defined, it is an observation and would be recorded as such in dwc:basisOfRecord. While I was working with the task group on dwcMaterialSample this concept was discussed. They can be "Born Digital" or derived from analog records, i.e. published or unpublished measured section records, field guides, area geological surveys, research diversity counts, etc; in fact, there is a huge backlog of observations in the written record extending back over a century and a half. In the biological world, observations recorded by iNaturalist or other device ID-type app can be recorded as an observation into GBIF and other aggregated datasets. This accounts for the overwhelming numbers of observational data recorded in those aggregated datasets, as documented by the "Bird" bias in GBIF, lots of bird-watchers out there! This has been an issue for neontological biodiversity research. However, in-situ fossils recorded in measured sections do have immense value and are overlooked by most researchers, especially measured sections where the original purpose was for non-paleo and were not collected for paelo.

**Comment by ekrimmel** [comment]
Thanks, @RogerBurkhalter – that's useful perspective!

@amillhouse is going to tweak this issue to better describe the topic, which will potentially be two happy hours. The first is scheduled for Feb 22 (see #42).

**Comment by amillhouse** [comment]
@ekrimmel Updated! ...do I need to do a "plan HH template" thing now?

**Comment by ekrimmel** [comment]
Awesome, thank you @amillhouse! Love the new title. You can use the "plan HH template" I created [here](https://github.com/paleo-data/happy-hours/issues/42) :)

I'm happy to help with any logistics! I just went ahead and updated the website topic and created a [shared notes doc](https://docs.google.com/document/d/1KtE2V34j0zzEhhT9sELBrAwnlIX-Bp-9a04wCG7G5vM/edit?usp=sharing).

**Comment by ekrimmel** [comment]
_Email sent just now:_

Please join us for the next biweekly Paleo Data Happy Hour on Thursday, February 22nd at 12pm Eastern (UTC-5). The Zoom link for this meeting and all meetings throughout 2024 is:
https://smithsonian.zoom.us/j/89262642228?pwd=R2h1TU1oOW9XQkVwR0RTeUFiUUpqUT09

This week our topic is shared data stewardship, i.e. how museums are managing data for shared collections. At the specimen level, this could include a fossil with part and counterpart stored/cataloged at different institutions. On the larger scale, multiple institutions could have hundreds or thousands of specimens collected from the same locality (or by the same person). A similar situation may occur when multiple institutions have casts of an in situ fossil located elsewhere. This happy hour will be an introduction to the types of shared collections described above in order to facilitate discussion on how we manage shared data. If you have an example from your own experience that you’d like to contribute, please add slide(s) with to the presentation [Shared Data Slides](https://docs.google.com/presentation/d/1tufIlcJNU_3x9i4SZ68oaxH66hypfbbj6PcLaupL47I/edit?usp=sharing).

More information for any of our Happy Hours, including links to shared agenda/notes and recordings, is [available on our website](https://paleo-data.github.io/happy-hours).
